version: '2'
services:
  sicapuc20201-app:
    image: sicapuc20201
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://sicapuc20201-postgresql:5432/sicapuc20201
      - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    ports:
      - 8080:8080
  sicapuc20201-postgresql:
    extends:
      file: postgresql.yml
      service: sicapuc20201-postgresql
